# Generated by Django 3.1.4 on 2020-12-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
